import { readFileSync } from 'node:fs'
import { expect, test, type Page } from '@playwright/test'
import { addKinds, begin, drawS1, endDrawing, guard, keyLink, RL, resumeAndGo, setKind, startSession } from './design-helpers'

const json = async (page: Page) => {
  const pre = page.getByTestId('kit-json')
  if (!(await pre.count())) await page.getByRole('button', { name: 'JSON', exact: true }).click()
  return JSON.parse((await pre.textContent()) ?? '{}')
}

test('D-12 add nodes by click; D-15, D-17 kind and rename; D-21 JSON; D-22 reload', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await addKinds(page, ['gateway', 'service', 'cache', 'sql'])
  await expect(page.getByTestId('kit-node-gateway-1')).toHaveAccessibleName('Gateway 1 · gateway')
  // [data-node-id] excludes the "kit-node-label" text input, whose testid also matches the "kit-node-" prefix.
  const cells = await page.locator('[data-testid^="kit-node-"][data-node-id]').evaluateAll(els => els.map(e => `${(e as HTMLElement).dataset.x},${(e as HTMLElement).dataset.y}`))
  expect(new Set(cells).size).toBe(4)
  await expect(page.getByTestId('kit-count')).toHaveText('4 nodes · 0 links')
  await expect(page.getByTestId('kit-node-sql-1')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('kit-node-sql-1')).toBeFocused()

  await keyLink(page, 'gateway-1', 'service-1')
  await setKind(page, 'gateway-1', 'service-1', 'async')
  await page.getByTestId('kit-node-sql-1').click()
  await page.getByRole('textbox', { name: 'Node label' }).fill('Redis counters')
  await page.getByRole('textbox', { name: 'Node label' }).press('Enter')
  await expect(page.getByTestId('kit-node-sql-1')).toHaveAccessibleName('Redis counters · sql')
  const j = await json(page)
  expect(await page.getByTestId('kit-json').textContent()).toContain('{"from":"gateway-1","to":"service-1","kind":"async"}')
  expect(j.layout).toBe('manual')
  expect(j.nodes).toHaveLength(4)
  for (const n of j.nodes) {
    expect(Number.isInteger(n.x) && Number.isInteger(n.y)).toBe(true)
  }
  for (const l of j.links) expect(j.nodes.map((n: { id: string }) => n.id)).toEqual(expect.arrayContaining([l.from, l.to]))

  await page.getByRole('group', { name: 'View' }).getByRole('button', { name: 'Iso' }).click()
  await page.clock.runFor(1000)
  await resumeAndGo(page, () => page.reload())
  await expect(page.getByTestId('session-phase')).toHaveText('drawing')
  await expect(page.getByRole('group', { name: 'View' }).getByRole('button', { name: 'Iso' })).toHaveAttribute('aria-pressed', 'true')
  expect(await json(page)).toEqual(j)
  await expect(page.getByTestId('kit-link-gateway-1-service-1')).toHaveAttribute('data-kind', 'async')
  check()
})

test('D-18 the whole flow without a mouse', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await page.getByRole('button', { name: 'Add browser', exact: true }).focus()
  for (let i = 0; i < 8; i++) await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('button', { name: 'Add lb', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  const lb = page.getByTestId('kit-node-lb-1')
  await expect(lb).toBeFocused()
  const x0 = Number(await lb.getAttribute('data-x'))
  const y0 = Number(await lb.getAttribute('data-y'))
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowDown')
  await expect(lb).toHaveAttribute('data-x', String(x0 + 2))
  await expect(lb).toHaveAttribute('data-y', String(y0 + 1))
  await page.getByRole('button', { name: 'Add service', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('kit-node-service-1')).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(lb).toBeFocused()
  await page.keyboard.press('l')
  await expect(page.getByTestId('kit-status')).toHaveText('Link from Lb 1: pick a target')
  await page.keyboard.press('Tab')
  await expect(page.getByTestId('kit-node-service-1')).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('kit-link-lb-1-service-1')).toHaveAttribute('data-kind', 'sync')
  await expect(page.getByTestId('kit-status')).toHaveText('')
  await lb.focus()
  await page.keyboard.press('l')
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('kit-status')).toHaveText('')
  await page.getByTestId('kit-node-service-1').focus()
  await page.keyboard.press('Delete')
  await expect(page.getByTestId('kit-count')).toHaveText('1 nodes · 0 links')
  await lb.focus()
  for (const k of ['1', '2', '5', '9', 't', 'd', 's', ' ']) await page.keyboard.press(k)
  await expect(page).toHaveURL(new RegExp(`/designs/session/${RL}$`))
  await page.getByRole('textbox', { name: 'Node label' }).focus()
  await page.keyboard.press('1')
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(new RegExp(`/designs/session/${RL}$`))
  await expect(page.getByTestId('kit-count')).toHaveText('1 nodes · 0 links')
  check()
})

test('D-20 2D and Iso render the same JSON', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await addKinds(page, ['gateway', 'service'])
  const before = await json(page)
  const view = page.getByRole('group', { name: 'View' })
  await view.getByRole('button', { name: 'Iso' }).click()
  await expect(view.getByRole('button', { name: 'Iso' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('kit-node-gateway-1')).toHaveAccessibleName('Gateway 1 · gateway')
  await view.getByRole('button', { name: '2D' }).click()
  expect(await json(page)).toEqual(before)
  check()
})

test('D-23 and Review Focus #2: changes persist within a second, the last of a burst wins', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await addKinds(page, ['queue', 'worker', 'sql'])
  await page.clock.runFor(1000)
  await resumeAndGo(page, () => page.reload())
  await expect(page.getByTestId('kit-count')).toHaveText('3 nodes · 0 links')
  check()
})

test('D-6/D-7 a locked canvas ignores the keyboard', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await addKinds(page, ['lb', 'service'])
  await keyLink(page, 'lb-1', 'service-1')
  const before = await json(page)
  await endDrawing(page)
  const canvas = page.getByTestId('kit-canvas')
  await expect(canvas).toHaveAttribute('data-locked', 'true')
  await expect(canvas).toHaveAttribute('aria-disabled', 'true')
  await expect(page.getByRole('button', { name: 'Add gateway', exact: true })).toBeDisabled()
  await page.getByTestId('kit-node-lb-1').focus()
  for (const k of ['ArrowRight', 'Delete', 'l']) await page.keyboard.press(k)
  expect(await json(page)).toEqual(before)
  check()
})

test('D-11 discard with nodes leaves nothing behind', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await addKinds(page, ['gateway', 'service'])
  await page.getByRole('button', { name: 'Discard session' }).click()
  await page.getByRole('dialog', { name: 'Discard this session?' }).getByRole('button', { name: 'Discard' }).click()
  await expect(page.getByTestId('session-phase')).toHaveText('setup')
  await page.getByRole('button', { name: 'Start · 45 min' }).click()
  await expect(page.getByTestId('kit-count')).toHaveText('0 nodes · 0 links')
  check()
})

test('D-13 drag a kind onto the canvas snaps to the cell under the pointer', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await page.getByRole('button', { name: 'Add queue', exact: true }).dragTo(page.getByTestId('kit-canvas'), { targetPosition: { x: 240, y: 240 } })
  const q = page.getByTestId('kit-node-queue-1')
  await expect(q).toHaveAttribute('data-x', '10')
  await expect(q).toHaveAttribute('data-y', '10')
  check()
})

test('D-14 connect with the mouse; D-16 move with the mouse; D-19 delete with the mouse', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await addKinds(page, ['gateway', 'service', 'cache', 'sql'])
  await page.getByTestId('kit-port-gateway-1').dragTo(page.getByTestId('kit-node-service-1'))
  const link = page.getByTestId('kit-link-gateway-1-service-1')
  await expect(link).toHaveAttribute('data-kind', 'sync')
  await expect(link).toHaveAccessibleName('Gateway 1 to Service 1 · sync')
  await expect(page.getByTestId('kit-count')).toHaveText('4 nodes · 1 links')
  // y kept within the canvas's own rendered height (min(70vh, 640px); 70vh of a 720px viewport is 504px).
  await page.getByTestId('kit-port-gateway-1').dragTo(page.getByTestId('kit-canvas'), { targetPosition: { x: 20, y: 400 } })
  await page.getByTestId('kit-port-gateway-1').dragTo(page.getByTestId('kit-node-gateway-1'))
  await page.getByTestId('kit-port-gateway-1').dragTo(page.getByTestId('kit-node-service-1'))
  await expect(page.getByTestId('kit-count')).toHaveText('4 nodes · 1 links')

  const cache = page.getByTestId('kit-node-cache-1')
  const [x0, y0] = [Number(await cache.getAttribute('data-x')), Number(await cache.getAttribute('data-y'))]
  const box = (await cache.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 48, box.y + box.height / 2 + 24, { steps: 4 })
  await page.mouse.up()
  await expect(cache).toHaveAttribute('data-x', String(x0 + 2))
  await expect(cache).toHaveAttribute('data-y', String(y0 + 1))

  await page.getByTestId('kit-node-gateway-1').click()
  await page.keyboard.press('Backspace')
  await expect(page.getByTestId('kit-node-gateway-1')).toHaveCount(0)
  await expect(page.getByTestId('kit-link-gateway-1-service-1')).toHaveCount(0)
  check()
})

test('D-7 a locked canvas ignores the mouse', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await addKinds(page, ['gateway'])
  await endDrawing(page)
  const g = page.getByTestId('kit-node-gateway-1')
  const [x0, y0] = [await g.getAttribute('data-x'), await g.getAttribute('data-y')]
  const box = (await g.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 100, box.y + box.height / 2 + 100, { steps: 4 })
  await page.mouse.up()
  await expect(g).toHaveAttribute('data-x', x0!)
  await expect(g).toHaveAttribute('data-y', y0!)
  check()
})

test('D-43 Export PNG downloads a real PNG named by design and day', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await startSession(page)
  await drawS1(page)
  const [dl] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export PNG', exact: true }).click()])
  expect(dl.suggestedFilename()).toBe('d-ratelimit-2026-10-11.png')
  const bytes = readFileSync((await dl.path())!)
  expect([...bytes.subarray(0, 8)]).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
  expect(bytes.length).toBeGreaterThan(1024)
  await endDrawing(page)
  const [again] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export PNG', exact: true }).click()])
  expect(again.suggestedFilename()).toBe('d-ratelimit-2026-10-11.png')
  check()
})
