import { expect, test, type Page } from '@playwright/test'
import { IST } from './helpers'
import {
  begin, CACHE, completeS1, drawS1, endDrawing, fillClose, guard, pick, resumeAndGo, RL, RL_TITLE, startSession,
} from './design-helpers'

const LENS = ['Load', 'Data', 'Consistency', 'Failure', 'Latency', 'Cost', 'Evolution']

/** S2 on d-cache, solo, lenses of the fake grade (C-DESIGN D-49). */
async function completeS2(page: Page) {
  await startSession(page, 'Solo', CACHE)
  await drawS1(page)
  await endDrawing(page)
  await fillClose(page, 'None, I answered all four')
  const dives = await page.getByTestId('session-score').getByRole('radiogroup').evaluateAll(gs => gs.slice(0, 4).map(g => g.getAttribute('aria-label') ?? ''))
  for (const [i, q] of dives.entries()) await pick(page, q, ([1, 1, 2, 1] as const)[i])
  for (const [i, l] of LENS.entries()) await pick(page, l, ([2, 1, 1, 1, 1, 0, 1] as const)[i])
  const row2 = page.getByTestId('session-tradeoff-row-2')
  await row2.getByRole('textbox', { name: 'Chose' }).fill('a')
  await row2.getByRole('textbox', { name: 'Over' }).fill('b')
  await row2.getByRole('textbox', { name: 'Because' }).fill('c')
  await page.getByRole('spinbutton', { name: 'Rubric (0–20)' }).fill('15')
  await page.getByRole('button', { name: 'Complete session' }).click()
  await expect(page.getByTestId('session-phase')).toHaveText('done')
}

test('D-48 empty evidence', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await page.goto('/designs')
  const ev = page.getByRole('region', { name: 'Design evidence' })
  const radar = ev.getByTestId('lens-radar')
  await expect(radar).toContainText('No sessions yet')
  for (const l of LENS) await expect(radar.getByText(l, { exact: true })).toBeVisible()
  await expect(ev.getByTestId('wall-cell')).toHaveCount(192)
  expect(await ev.locator('[data-testid="wall-cell"][data-state="none"]').count()).toBe(192)
  await expect(ev.getByText('0 of 192 answered in full')).toBeVisible()
  await expect(ev.getByTestId('shelf')).toContainText('No diagrams yet')
  await expect(ev.getByTestId('design-vocab')).toHaveText('Vocabulary · 0 of 38 kinds used')
  check()
})

test('D-49…D-53, D-55 evidence after S1 then S2', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await completeS1(page)
  await resumeAndGo(page, () => page.goto('/designs'))
  const ev = page.getByRole('region', { name: 'Design evidence' })
  const radar = ev.getByTestId('lens-radar')
  const one = 'Load 2.0, Data 1.0, Consistency 1.0, Failure 0.0, Latency 2.0, Cost 1.0, Evolution 1.0'
  await expect(radar).toHaveAccessibleName(`Lens radar · last 6: ${one} · all-time: ${one}`)
  const cell = (dive: number) => ev.locator(`[data-testid="wall-cell"][data-design="${RL}"][data-dive="${dive}"]`)
  for (const [dive, state] of [[1, 'ok'], [2, 'glow'], [3, 'ok'], [4, 'none']] as const) await expect(cell(dive)).toHaveAttribute('data-state', state)
  await expect(cell(1)).toHaveAccessibleName(`${RL_TITLE} · deep dive 1 · answered`)
  expect(await ev.getByTestId('wall-cell').nth(6).getAttribute('data-design')).toBe(RL)
  await expect(ev.getByText('2 of 192 answered in full')).toBeVisible()
  await expect(page.getByTestId('designs-sundays')).toHaveText('2 deep dives answered')
  const thumb = ev.getByTestId('shelf-tier-2').getByTestId('shelf-thumb')
  await expect(thumb).toHaveAccessibleName(`${RL_TITLE} · 2026-10-11 · 4 nodes`)
  await expect(ev.getByTestId('design-vocab')).toHaveText('Vocabulary · 4 of 38 kinds used')
  await resumeAndGo(page, () => page.reload())
  await expect(ev.getByTestId('lens-radar')).toHaveAccessibleName(`Lens radar · last 6: ${one} · all-time: ${one}`)
  await thumb.click()
  await expect(page).toHaveURL(new RegExp(`/designs/session/${RL}\\?session=`))
  await expect(page.getByTestId('session-yours')).toBeVisible()
  await expect(page.getByTestId('session-reference')).toBeVisible()
  await expect(page.getByTestId('session-diff')).toBeVisible()

  await completeS2(page)
  await resumeAndGo(page, () => page.goto('/designs'))
  const two = 'Load 2.0, Data 1.0, Consistency 1.0, Failure 0.5, Latency 1.5, Cost 0.5, Evolution 1.0'
  await expect(ev.getByTestId('lens-radar')).toHaveAccessibleName(`Lens radar · last 6: ${two} · all-time: ${two}`)
  expect(JSON.parse((await ev.getByTestId('lens-radar').getAttribute('data-mean'))!)).toEqual({ load: 2, data: 1, consistency: 1, failure: 0.5, latency: 1.5, cost: 0.5, evolution: 1 })
  await expect(ev.getByTestId('lens-spark-failure')).toHaveAccessibleName('Failure trend: 0, 1')
  await cell(1).click()
  await expect(page).toHaveURL(new RegExp(`/designs/session/${RL}\\?session=`))
  check()
})

test('D-46/D-47 redesign queue, due link, a passing redesign', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await completeS1(page)
  await resumeAndGo(page, () => page.goto('/designs'))
  const row = page.getByTestId(`design-redesign-${RL}`)
  await expect(page.getByRole('region', { name: 'Redesigns' })).toBeVisible()
  await expect(row).toContainText(RL_TITLE)
  await expect(row).toContainText('due 2026-11-10')
  await expect(row).toContainText('queued')
  await expect(row).toContainText('Read: Stripe rate limiter blog post')
  await page.clock.setSystemTime(IST('2026-11-10T09:00:00'))
  await resumeAndGo(page, () => page.reload())
  await expect(row.getByText('due', { exact: true })).toBeVisible()
  await row.getByRole('link', { name: `Start redesign: ${RL_TITLE}` }).click()
  await expect(page).toHaveURL(new RegExp(`/designs/session/${RL}$`))
  await expect(page.getByTestId('session-setup')).toContainText('Redesign pass · previous rubric 12')
  await page.getByRole('button', { name: 'Start · 45 min' }).click()
  await page.getByRole('button', { name: 'Add gateway', exact: true }).click()
  await endDrawing(page)
  await fillClose(page, 'None, I answered all four')
  const dives = await page.getByTestId('session-score').getByRole('radiogroup').evaluateAll(gs => gs.slice(0, 4).map(g => g.getAttribute('aria-label') ?? ''))
  for (const q of dives) await pick(page, q, 2)
  for (const l of LENS) await pick(page, l, 1)
  const row2 = page.getByTestId('session-tradeoff-row-2')
  await row2.getByRole('textbox', { name: 'Chose' }).fill('a')
  await row2.getByRole('textbox', { name: 'Over' }).fill('b')
  await row2.getByRole('textbox', { name: 'Because' }).fill('c')
  await page.getByRole('spinbutton', { name: 'Rubric (0–20)' }).fill('16')
  await page.getByRole('button', { name: 'Complete session' }).click()
  await expect(page.getByTestId('session-phase')).toHaveText('done')
  await expect(page.getByTestId('toast').filter({ hasText: '+20 xp' })).toHaveCount(0)
  await resumeAndGo(page, () => page.goto('/designs'))
  await expect(page.getByTestId(`design-redesign-${RL}`)).toHaveCount(0)
  await expect(page.getByTestId('design-redesign-rate')).toHaveText('Redesign pass rate · 1 / 1')
  check()
})

test('C-INT §7 I-26: a due redesign shows up in Today\'s Redo drawer as a link and opens the design session', async ({ page }) => {
  const check = guard(page)
  await begin(page)
  await completeS1(page)
  await resumeAndGo(page, () => page.goto('/'))
  await expect(page.getByTestId('today-redo-drawer')).toHaveCount(0)
  await page.clock.setSystemTime(IST('2026-11-10T09:00:00'))
  await resumeAndGo(page, () => page.reload())
  const toggle = page.getByTestId('today-redo-toggle')
  await expect(toggle).toContainText('Redo · 1')
  await toggle.click()
  const row = page.getByTestId(`today-redo-design-${RL}`)
  await expect(row).toHaveAccessibleName('Redesign Distributed rate limiter and API gateway')
  await expect(row).toHaveAttribute('href', `/designs/session/${RL}`)
  await expect(row).toHaveText('Distributed rate limiter and API gateway · redesign · previous rubric 12/20')
  await row.click()
  await expect(page).toHaveURL(new RegExp(`/designs/session/${RL}$`))
  check()
})
