import { readFileSync } from 'node:fs'
import { expect, test, type Locator, type Page } from './fixtures'
import { dojoBaseUrl } from '../../dojoPort'
import { idbAll, onboard } from './helpers'

// DSA labs acceptance, written from the binding contract (dojo-wt-docs contracts/labs.md §10) on the live plan,
// start 2026-10-05. Names are matched exactly (the contract's names are the selectors).

const ALLOWED = new Set<string>() // _common rule 1; fonts are self-hosted (public/fonts)

/** Fails the test on console errors, page errors, or a request to any origin but the app's (S49). */
function watch(page: Page) {
  const base = new URL(test.info().project.use.baseURL ?? dojoBaseUrl(process.env)).origin
  const problems: string[] = []
  page.on('console', m => m.type() === 'error' && problems.push(`console: ${m.text()}`))
  page.on('pageerror', e => problems.push(`pageerror: ${e.message}`))
  page.on('request', r => {
    const url = r.url()
    if (url.startsWith('data:') || url.startsWith('blob:')) return
    const origin = new URL(url).origin
    if (origin !== base && !ALLOWED.has(origin)) problems.push(`request: ${url}`)
  })
  return () => expect(problems).toEqual([])
}

const exact = (name: string) => ({ name, exact: true })
const player = (scope: Page | Locator) => scope.getByTestId('lab-player').first()
const counter = (scope: Page | Locator) => scope.getByTestId('lab-step-counter').first()
const walks = (page: Page) => page.getByRole('list', exact('Walkthroughs')).getByRole('listitem')
/** The Walkthroughs list item whose title is exactly `title` ("Binary search" ≠ "Binary search on the answer"). */
const item = (page: Page, title: string) => walks(page).filter({ has: page.getByText(title, { exact: true }) })

async function ownInput(page: Page, title: string, fields: Record<string, string>) {
  await item(page, title).getByRole('button', exact('Own input')).click()
  const form = page.getByRole('form', exact(`Own input: ${title}`))
  for (const [label, value] of Object.entries(fields)) await form.getByLabel(label, { exact: true }).fill(value)
  await form.getByRole('button', exact('Trace')).click()
}

/** Answers every open question with the correct choice (the dev-only data-answer="correct" marker). */
async function answerAll(page: Page, scope: Locator, wrongFirst = false) {
  const predict = scope.getByTestId('lab-predict')
  let first = true
  for (let i = 0; i < 300; i++) {
    if (await predict.getByTestId('lab-predict-result').isVisible()) return
    const open = predict.locator('button[data-answer="correct"]:enabled')
    if (await open.count()) {
      if (first && wrongFirst) await predict.locator('.lab-predict-choices button:enabled:not([data-answer])').first().click()
      else await open.click()
      first = false
    } else {
      await scope.getByRole('button', exact('Step forward')).click()
    }
  }
  throw new Error('predict run did not finish')
}

test.describe('Atlas navigation and matrix', () => {
  test('S1/S2: the Atlas tab and its key open /atlas; typing the key in the search box does not navigate', async ({ page }) => {
    const ok = watch(page)
    await onboard(page, '2026-10-05')
    await page.getByTestId('more-button').click()
    const tab = page.getByRole('menuitem', exact('Atlas'))
    const key = await tab.getAttribute('aria-keyshortcuts')
    expect(key).toBeTruthy()
    await tab.click()
    await expect(page).toHaveURL(/\/atlas$/)
    await expect(page.getByTestId('atlas-summary')).toHaveText('16 atoms · 36 patterns · you have predicted 0')
    await expect(page.locator('[data-testid^="atlas-row-"]')).toHaveCount(36)
    await expect(page.getByRole('progressbar', exact('Patterns predicted'))).toHaveAttribute('aria-valuenow', '0')
    await page.goto('/')
    await page.getByTestId('xp-total').waitFor({ state: 'attached' })
    await page.locator('body').press(key!)
    await expect(page).toHaveURL(/\/atlas$/)
    await page.getByRole('searchbox', exact('Search patterns or problems')).press(key!)
    await expect(page.getByRole('searchbox', exact('Search patterns or problems'))).toHaveValue(key!)
    await expect(page).toHaveURL(/\/atlas$/)
    ok()
  })

  test('S3/S4/S5/S6: deep link, reload, bad link, cells, a row without walkthroughs', async ({ page }) => {
    const ok = watch(page)
    await onboard(page, '2026-10-05')
    await page.goto('/atlas?pattern=shortest-path')
    await expect(page.getByRole('complementary', exact('Pattern: Shortest path'))).toBeVisible()
    await expect(walks(page)).toHaveCount(2)
    await expect(page.getByTestId('atlas-coverage')).toHaveText(/^Coverage: live/)
    await page.reload()
    await expect(page.getByTestId('atlas-detail')).toBeVisible()
    await page.goto('/atlas?pattern=nope')
    await expect(page.getByTestId('atlas-matrix')).toBeVisible()
    await expect(page.getByTestId('atlas-detail')).toHaveCount(0)
    await expect(page.locator('[data-testid^="atlas-cell-binary-search-"][data-kind="main"]')).toHaveCount(2)
    await expect(page.getByTestId('atlas-cell-binary-search-NUMLN')).toHaveAttribute('data-kind', 'main')
    await page.getByRole('button', exact('Flow · matching')).click()
    await expect(page.getByTestId('atlas-detail')).toContainText('No walkthrough yet')
    await expect(page.getByTestId('atlas-coverage')).toHaveText('Coverage: gap · edge labels show one number; needs cap/flow pairs')
    await expect(page.getByRole('button', exact('Trace my own input'))).toBeDisabled()
    await expect(page.getByTestId('atlas-last-picture')).toHaveText('No picture generated yet.')
    ok()
  })

  test('S7/S8/S9/S10/S11: problems, sort, filter, number, classify fallback', async ({ page }) => {
    const ok = watch(page)
    await onboard(page, '2026-10-05')
    await page.goto('/atlas')
    await page.getByRole('button', exact('Topo sort')).click()
    await page.getByRole('list', exact('Problems')).getByRole('link', exact('207 Course Schedule')).click()
    await expect(page).toHaveURL(/\/do\/p207$/)
    await page.goto('/atlas')
    await page.getByRole('button', exact('Sort by problems left')).click()
    const lefts = async () => (await page.locator('.am-left').allTextContents()).map(Number)
    expect(await lefts()).toEqual([...(await lefts())].sort((a, b) => b - a))
    await page.reload()
    await expect(page.getByRole('button', exact('Sort by problems left'))).toHaveAttribute('aria-pressed', 'true')
    await page.getByRole('button', exact('Sort by problems left')).click()
    await expect(page.getByRole('rowheader').first()).toHaveText('Two pointers')
    await expect(page.getByRole('rowheader').last()).toHaveText('Sieve · primes')
    const box = page.getByRole('searchbox', exact('Search patterns or problems'))
    await box.fill('dp')
    await expect(page.getByRole('rowheader')).toHaveText(['DP · memo', 'DP · tabulation', 'DP · bitmask'])
    await box.press('Enter')
    await expect(page.getByRole('button', exact('DP · memo'))).toHaveAttribute('aria-pressed', 'true')
    await box.fill('')
    await expect(page.getByRole('rowheader')).toHaveCount(36)
    await box.fill('743')
    await box.press('Enter')
    await expect(page.getByRole('list', exact('Problems')).getByRole('link', exact('743 Network Delay Time'))).toBeVisible()
    await box.fill('shortest path with k stops across flights zzz')
    await expect(page.getByTestId('atlas-search-status')).toHaveText('No local match. Press Enter to ask classify.')
    await box.press('Enter')
    await expect(page.getByTestId('atlas-search-status')).toHaveText(/^Matched by classify: /)
    await expect(page.getByRole('rowheader')).toHaveCount(36)
    ok()
  })
})

test.describe('Player', () => {
  test('S12/S13/S15: own input, stepping, captions, play to the end marks seen', async ({ page }) => {
    const ok = watch(page)
    await onboard(page, '2026-10-05')
    await page.goto('/atlas?pattern=binary-search')
    await ownInput(page, 'Binary search', { Values: '1,3,5,7,9', Target: '7' })
    const p = page.getByRole('region', exact('Player: Binary search'))
    await expect(p.getByTestId('lab-complexity')).toHaveText('O(log n) · O(1)')
    await expect(counter(p)).toHaveText('STEP 0 / 13')
    const fwd = p.getByRole('button', exact('Step forward'))
    await fwd.click()
    await fwd.click()
    await expect(p.getByTestId('lab-caption')).toHaveText('Search for 7 between lo and hi.')
    await fwd.click()
    await fwd.click()
    await expect(p.getByTestId('lab-caption')).toHaveText('mid = 2, a[mid] = 5.')
    for (let i = 0; i < 5; i++) await fwd.click()
    const at9 = await p.getByTestId('lab-caption').textContent()
    await fwd.click()
    await fwd.click()
    await p.getByRole('button', exact('Step back')).click()
    await p.getByRole('button', exact('Step back')).click()
    await expect(counter(p)).toHaveText('STEP 9 / 13')
    await expect(p.getByTestId('lab-caption')).toHaveText(at9 ?? '')
    await p.getByRole('button', exact('Last step')).click()
    await expect(p.getByTestId('lab-caption')).toHaveText('Found 7 at index 3.')
    await expect(p.getByRole('button', exact('Replay'))).toBeVisible()
    await expect(page.getByTestId('atlas-row-binary-search')).toHaveAttribute('data-state', 'none')
    await p.getByRole('button', exact('First step')).click()
    await p.getByRole('button', exact('Play')).click()
    await expect(p.getByRole('button', exact('Pause'))).toBeVisible()
    await expect(counter(p)).toHaveText('STEP 13 / 13', { timeout: 9_000 })
    await expect(p.getByRole('button', exact('Replay'))).toBeVisible()
    await expect(page.getByTestId('atlas-row-binary-search')).toHaveAttribute('data-state', 'seen')
    await expect(page.getByTestId('atlas-summary')).toHaveText(/predicted 0$/)
    ok()
  })

  test('S14/S17: keys step without scrolling; 4× reaches the end fast', async ({ page }) => {
    await onboard(page, '2026-10-05')
    await page.goto('/atlas?pattern=binary-search')
    await item(page, 'Binary search').getByRole('button', exact('Play')).click()
    const p = page.getByRole('region', exact('Player: Binary search'))
    await p.getByRole('button', exact('Pause')).click()
    await p.getByRole('button', exact('First step')).click()
    await p.getByTestId('lab-caption').click()
    const y = await page.evaluate(() => window.scrollY)
    for (const k of ['ArrowRight', 'ArrowRight', 'ArrowRight', 'ArrowLeft']) await page.keyboard.press(k)
    await expect(counter(p)).toHaveText('STEP 2 / 22')
    expect(await page.evaluate(() => window.scrollY)).toBe(y)
    await page.keyboard.press('Space')
    await expect(p.getByRole('button', exact('Pause'))).toBeVisible()
    await page.keyboard.press('Space')
    await expect(p.getByRole('button', exact('Play'))).toBeVisible()
    await p.getByRole('button', exact('First step')).click()
    await p.getByRole('combobox', exact('Speed')).selectOption('4×')
    await p.getByRole('button', exact('Play')).click()
    await expect(counter(p)).toHaveText('STEP 22 / 22', { timeout: 5_000 })
  })

  test('S18/S20/S25: predict all right turns the row green and survives reload; controls lock at a question', async ({ page }) => {
    const ok = watch(page)
    await onboard(page, '2026-10-05')
    await page.goto('/atlas?pattern=binary-search')
    await ownInput(page, 'Binary search', { Values: '1,3,5,7,9', Target: '7' })
    const p = page.getByRole('region', exact('Player: Binary search'))
    await p.getByRole('button', exact('Predict')).click()
    await p.getByRole('button', exact('Play')).click()
    const q = p.getByTestId('lab-predict')
    await expect(q.getByRole('heading', exact('What happens next?'))).toBeVisible()
    await expect(counter(p)).toHaveText('STEP 5 / 13')
    await expect(q.locator('.lab-predict-choices button')).toHaveText(['Mark done', 'Mark bad', 'Mark path'])
    for (const name of ['Step forward', 'Play', 'Last step']) await expect(p.getByRole('button', exact(name))).toBeDisabled()
    await p.getByRole('button', exact('Step back')).click()
    await expect(counter(p)).toHaveText('STEP 4 / 13')
    await p.getByRole('button', exact('Step forward')).click()
    await q.getByRole('button', exact('Mark bad')).click()
    await expect(q.getByTestId('lab-predict-feedback')).toHaveText('Right.')
    await expect(q.getByTestId('lab-predict-score')).toHaveText('1 / 1 of 4')
    await answerAll(page, p)
    await expect(q.getByTestId('lab-predict-result')).toHaveText('4 / 4 · 100% Predicted')
    await expect(page.getByTestId('atlas-row-binary-search')).toHaveAttribute('data-state', 'predicted')
    await expect(page.getByTestId('atlas-summary')).toHaveText(/you have predicted 1$/)
    await page.reload()
    await expect(page.getByTestId('atlas-row-binary-search')).toHaveAttribute('data-state', 'predicted')
    ok()
  })

  test('S19/S21/S22: a wrong answer, compare and visit questions', async ({ page }) => {
    await onboard(page, '2026-10-05')
    await page.goto('/atlas?pattern=binary-search')
    await ownInput(page, 'Binary search', { Values: '1,3,5,7,9', Target: '7' })
    let p = page.getByRole('region', exact('Player: Binary search'))
    await p.getByRole('button', exact('Predict')).click()
    await answerAll(page, p, true)
    await expect(p.getByTestId('lab-predict-result')).toHaveText('3 / 4 · 75% Need 80% — try again')
    await expect(page.getByTestId('atlas-row-binary-search')).toHaveAttribute('data-state', 'seen')
    await page.goto('/atlas?pattern=sorting')
    await ownInput(page, 'Bubble sort', { Values: '3,1,2' })
    p = page.getByRole('region', exact('Player: Bubble sort'))
    await p.getByRole('button', exact('Predict')).click()
    await p.getByRole('button', exact('Step forward')).click()
    await expect(p.getByTestId('lab-predict')).toContainText('Compare a[0] = 3 with a[1] = 1')
    await answerAll(page, p)
    await expect(p.getByTestId('lab-predict-result')).toHaveText('6 / 6 · 100% Predicted')
    await page.goto('/atlas?pattern=bfs-dfs')
    await ownInput(page, 'Breadth-first search', { Edges: 'A-B, A-C, B-D', 'Start node': 'A' })
    p = page.getByRole('region', exact('Player: Breadth-first search'))
    await p.getByRole('button', exact('Predict')).click()
    await p.getByRole('button', exact('Play')).click()
    await expect(p.getByTestId('lab-predict').locator('.lab-predict-choices button')).toHaveText(['A', 'B', 'C'])
    await answerAll(page, p)
    await expect(p.getByTestId('lab-predict-result')).toHaveText('3 / 3 · 100% Predicted')
  })
})

test.describe('Two-up, own input, snapshot', () => {
  test('S27/S28/S30: lock-step, shared own input, different-inputs note', async ({ page }) => {
    await onboard(page, '2026-10-05')
    await page.goto('/atlas?pattern=shortest-path')
    await item(page, "Dijkstra's shortest paths").getByRole('button', exact('Two-up')).click()
    const two = page.getByRole('region', exact('Two-up'))
    await expect(two.getByTestId('lab-two-up-counter')).toHaveText('STEP 0 / 54')
    await expect(two.getByTestId('lab-step-counter')).toHaveText(['STEP 0 / 51', 'STEP 0 / 54'])
    await expect(two.getByTestId('lab-two-up-note')).toHaveCount(0)
    for (let i = 0; i < 3; i++) await two.getByRole('button', exact('Step forward')).click()
    await expect(two.getByTestId('lab-step-counter')).toHaveText(['STEP 3 / 51', 'STEP 3 / 54'])
    const [dl] = await Promise.all([page.waitForEvent('download'), two.getByTestId('lab-player').first().getByRole('button', exact('Snapshot')).click()])
    expect(dl.suggestedFilename()).toBe('dojo-dijkstra-step-3-of-51.png')
    await two.getByRole('button', exact('Last step')).click()
    await expect(two.getByTestId('lab-step-counter')).toHaveText(['STEP 51 / 51', 'STEP 54 / 54'])
    await expect(two.getByRole('button', exact('Predict'))).toBeDisabled()
    await two.getByRole('button', exact('Own input')).click()
    const form = two.getByRole('form', exact("Own input: Dijkstra's shortest paths"))
    await form.getByLabel('Edges', { exact: true }).fill('A-B:1, A-C:4, B-C:2, C-D:1')
    await form.getByLabel('Start node', { exact: true }).fill('A')
    await form.getByRole('button', exact('Trace')).click()
    await expect(two.getByTestId('lab-step-counter')).toHaveText(['STEP 0 / 31', 'STEP 0 / 31'])
    await page.goto('/atlas?pattern=binary-search')
    await item(page, 'Binary search').getByRole('button', exact('Two-up')).click()
    await page.getByRole('combobox', exact('Compare with')).selectOption({ label: 'Min-heap · push with sift-up' })
    await expect(page.getByTestId('lab-two-up-note')).toHaveText('Different inputs: these walkthroughs take different input shapes.')
  })

  test('S32/S33/S35: validation, remembered input, PNG snapshot', async ({ page }) => {
    const ok = watch(page)
    await onboard(page, '2026-10-05')
    await page.goto('/atlas?pattern=binary-search')
    await ownInput(page, 'Binary search', { Values: '1,3,x' })
    await expect(page.getByTestId('lab-own-input-error')).toHaveText('Only whole numbers from -999 to 999, separated by commas.')
    await expect(page.getByLabel('Values', { exact: true })).toHaveAttribute('aria-invalid', 'true')
    const form = page.getByRole('form', exact('Own input: Binary search'))
    await form.getByLabel('Values', { exact: true }).fill('1,3,5,7,9')
    await form.getByLabel('Target', { exact: true }).fill('7')
    await form.getByRole('button', exact('Trace')).click()
    const p = page.getByRole('region', exact('Player: Binary search'))
    await expect(counter(p)).toHaveText('STEP 0 / 13')
    await p.getByRole('button', exact('Last step')).click()
    const [dl] = await Promise.all([page.waitForEvent('download'), p.getByRole('button', exact('Snapshot')).click()])
    expect(dl.suggestedFilename()).toBe('dojo-binary-search-step-13-of-13.png')
    const bytes = readFileSync((await dl.path())!)
    expect([...bytes.subarray(0, 4)]).toEqual([0x89, 0x50, 0x4e, 0x47])
    expect(bytes.readUInt32BE(16)).toBeGreaterThanOrEqual(320)
    await page.reload()
    await ownInput(page, 'Binary search', {})
    await expect(page.getByLabel('Values', { exact: true })).toHaveValue('1,3,5,7,9')
    await page.getByRole('button', exact('Reset to default')).click()
    await expect(page.getByLabel('Values', { exact: true })).toHaveValue('1, 3, 4, 7, 9, 12, 15, 18, 21')
    await expect(counter(page.getByRole('region', exact('Player: Binary search')))).toHaveText('STEP 0 / 22')
    ok()
  })
})

test.describe('DSA warm-up and Do', () => {
  test('S36: a topic opens with its free warm-up; watching it changes no XP and marks the Atlas row', async ({ page }) => {
    const ok = watch(page)
    await onboard(page, '2026-10-05')
    const xp = await page.getByTestId('xp-total').textContent()
    await page.goto('/dsa?topic=2')
    const warm = page.getByRole('region', exact('Warm-up'))
    await expect(warm).toContainText('Warm-up · free')
    await expect(warm.getByRole('group', exact('Warm-up walkthroughs')).getByRole('button', { pressed: true })).toHaveText(['Topological sort · Kahn'])
    await expect(counter(warm)).toHaveText('STEP 0 / 56')
    await page.waitForTimeout(1500)
    await expect(counter(warm)).toHaveText('STEP 0 / 56')
    await warm.getByRole('combobox', exact('Speed')).selectOption('4×')
    await warm.getByRole('button', exact('Play')).click()
    await expect(counter(warm)).toHaveText('STEP 56 / 56', { timeout: 20_000 })
    await page.goto('/')
    await expect(page.getByTestId('xp-total')).toHaveText(xp ?? '')
    await page.goto('/atlas')
    await expect(page.getByTestId('atlas-row-topo-sort')).toHaveAttribute('data-state', 'seen')
    ok()
  })

  test('S40/S41/S42: the Approaches strip on Do', async ({ page }) => {
    await onboard(page, '2026-10-05')
    await page.goto('/do/p743')
    const strip = page.getByRole('region', exact('Approaches'))
    await expect(strip.getByTestId('dsa-approach-chip')).toHaveCount(2)
    await expect(strip.getByTestId('lab-player')).toHaveCount(0)
    await strip.getByRole('button', exact('Dijkstra · O(E log V) · best')).click()
    await expect(counter(strip)).toHaveText('STEP 0 / 51')
    await expect(strip.getByRole('button', exact('Dijkstra · O(E log V) · best'))).toHaveAttribute('aria-pressed', 'true')
    await strip.getByRole('button', exact('Pick two')).click()
    await strip.getByRole('button', exact('Bellman-Ford · O(V·E)')).click()
    await strip.getByRole('button', exact('Dijkstra · O(E log V) · best')).click()
    const two = strip.getByRole('region', exact('Two-up'))
    await expect(two.getByTestId('lab-two-up-counter')).toHaveText('STEP 0 / 54')
    await expect(two.getByTestId('lab-player').nth(0)).toHaveAttribute('data-walkthrough', 'bellmanFord')
    await expect(two.getByTestId('lab-player').nth(1)).toHaveAttribute('data-walkthrough', 'dijkstra')
    await expect(strip.getByRole('button', exact('Pick two'))).toHaveAttribute('aria-pressed', 'false')
    await page.goto('/do/p322')
    const s2 = page.getByRole('region', exact('Approaches'))
    await s2.getByRole('button', exact('Brute recursion · O(c^a)')).click()
    await expect(s2.getByRole('status')).toHaveText('No library picture for this approach yet.')
    await s2.getByRole('button', exact('Pick two')).click()
    await expect(s2.getByRole('button', exact('Brute recursion · O(c^a)'))).toBeDisabled()
    await expect(s2.getByRole('button', exact('Tabulation · O(a·c) · best'))).toBeEnabled()
  })

  test('S43/S44/S45: which approach, coverage and the avoided cube', async ({ page }) => {
    await onboard(page, '2026-10-05')
    // tickets with approaches but no problem pack: a pack ticket's Solved waits for Submit 5/5 (runner §4)
    await page.goto('/do/p1976')
    await page.getByRole('button', exact('Solved ✓')).click()
    const q = page.getByRole('group', exact('Which approach did you use?'))
    await expect(q.getByRole('button')).toHaveText(['DFS all paths · O(2^V)', 'Dijkstra + path count · O(E log V) · best', 'Other', 'Back to Board'])
    await q.getByRole('button', exact('Dijkstra + path count · O(E log V) · best')).click()
    await expect(q.getByRole('button', exact('Dijkstra + path count · O(E log V) · best'))).toHaveAttribute('aria-pressed', 'true')
    await expect.poll(async () => (await idbAll<{ approach?: string }>(page, 'sessions')).map(s => s.approach)).toEqual(['dijkstra'])
    await page.goto('/atlas?pattern=shortest-path')
    await expect(page.getByTestId('atlas-approach-coverage')).toHaveText('Reached for 1 · best answer 1')
    await expect(page.getByTestId('atlas-row-shortest-path')).toHaveAttribute('data-coverage', 'ok')
    await page.goto('/do/p1514')
    await page.getByRole('button', exact('Solved ✓')).click()
    await page.getByRole('group', exact('Which approach did you use?')).getByRole('button', exact('Other')).click()
    await expect.poll(async () => (await idbAll<{ approach?: string }>(page, 'sessions')).length).toBe(2)
    await page.goto('/do/p253')
    await page.getByRole('button', exact('Solved with help')).click()
    await page.getByRole('group', exact('Which approach did you use?')).getByRole('button', exact('Min-heap of ends · O(n log n)')).click()
    await expect.poll(async () => (await idbAll<{ approach?: string }>(page, 'sessions')).map(s => s.approach)).toEqual(['dijkstra', 'other', 'heap'])
    await page.goto('/atlas?pattern=heap-pq')
    await expect(page.getByTestId('atlas-approach-coverage')).toHaveText('Reached for 1 · best answer 0')
    const sessions = await idbAll<{ ticketId: string; approach?: string }>(page, 'sessions')
    expect(sessions.map(s => [s.ticketId, s.approach])).toEqual([['p1976', 'dijkstra'], ['p1514', 'other'], ['p253', 'heap']])
    await page.goto('/do/p787')
    await page.getByRole('button', exact('Give up')).click()
    await expect(page.getByRole('group', exact('Which approach did you use?'))).toHaveCount(0)
  })
})

test.describe('Cross-cutting', () => {
  test('S46: reduced motion plays at 900 ms per step', async ({ browser }) => {
    for (const reducedMotion of ['reduce', 'no-preference'] as const) {
      const ctx = await browser.newContext({ reducedMotion })
      const page = await ctx.newPage()
      await onboard(page, '2026-10-05')
      await page.goto('/atlas?pattern=binary-search')
      await item(page, 'Binary search').getByRole('button', exact('Play')).click()
      const p = page.getByRole('region', exact('Player: Binary search'))
      await page.waitForTimeout(2000)
      const k = Number((await counter(p).textContent())!.match(/STEP (\d+)/)![1])
      if (reducedMotion === 'reduce') expect(k).toBeLessThanOrEqual(3)
      else expect(k).toBeGreaterThanOrEqual(2)
      await ctx.close()
    }
  })

  test('S47: 560 px never scrolls the page sideways', async ({ page }) => {
    await page.setViewportSize({ width: 560, height: 900 })
    await onboard(page, '2026-10-05')
    const flat = async () => {
      const { sw, cw } = await page.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth }))
      expect(sw).toBeLessThanOrEqual(cw)
    }
    await page.goto('/atlas?pattern=shortest-path')
    await item(page, "Dijkstra's shortest paths").getByRole('button', exact('Two-up')).click()
    await expect(page.getByTestId('lab-player')).toHaveCount(2)
    await flat()
    const boxes = await page.getByTestId('lab-player').evaluateAll(els => els.map(e => e.getBoundingClientRect().top))
    expect(boxes[1]).toBeGreaterThan(boxes[0])
    await page.goto('/dsa?topic=1')
    await expect(page.getByTestId('dsa-warmup')).toBeVisible()
    await flat()
    await page.goto('/do/p743')
    const strip = page.getByRole('region', exact('Approaches'))
    await strip.getByRole('button', exact('Pick two')).click()
    await strip.getByRole('button', exact('Bellman-Ford · O(V·E)')).click()
    await strip.getByRole('button', exact('Dijkstra · O(E log V) · best')).click()
    await expect(strip.getByTestId('lab-player')).toHaveCount(2)
    await flat()
  })

  test('S48: keyboard only', async ({ page }) => {
    await onboard(page, '2026-10-05')
    await page.goto('/atlas')
    await page.getByRole('button', exact('Greedy')).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', exact('Greedy'))).toBeFocused()
    const play = item(page, 'Greedy · interval scheduling').getByRole('button', exact('Play'))
    for (let i = 0; i < 20 && !(await play.evaluate(el => el === document.activeElement)); i++) await page.keyboard.press('Tab')
    await page.keyboard.press('Enter')
    const p = page.getByRole('region', exact('Player: Greedy · interval scheduling'))
    const pause = p.getByRole('button', exact('Pause'))
    await expect(pause).toBeVisible()
    for (let i = 0; i < 20 && !(await pause.evaluate(el => el === document.activeElement).catch(() => false)); i++) await page.keyboard.press('Tab')
    await page.keyboard.press('Space')
    await expect(p.getByRole('button', { name: /^(Play|Replay)$/ })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('atlas-detail')).toHaveCount(0)
    await expect(page.getByRole('button', exact('Greedy'))).toBeFocused()
  })
})
