import { expect, test, type Page } from './fixtures'
import { IST, idbAll, onboard } from './helpers'
import { ownTextElements } from './type-scan'

// ux spec section 3 (the study session), contract UX-06..UX-11, on a fake clock: time flows, and
// fastForward jumps it (the app derives every phase from the wall clock, so a jump credits every block).
const T0 = IST('2026-10-06T21:10:00')
const CARD = '/do/p200'

async function begin(page: Page) {
  await page.clock.install({ time: T0 })
  await onboard(page, '2026-10-05')
  await page.goto(CARD)
  await expect(page.getByTestId('screen-do')).toHaveAttribute('data-ready', 'true')
}
async function startSession(page: Page, opts: { goal?: string; cycle?: string } = {}) {
  await page.getByRole('button', { name: 'Start session' }).click()
  const dlg = page.getByRole('dialog', { name: 'Plan this session' })
  await expect(dlg).toBeVisible()
  if (opts.goal) await dlg.getByLabel('This session I will').fill(opts.goal)
  if (opts.cycle) await dlg.getByRole('radio', { name: opts.cycle }).check()
  await dlg.getByRole('button', { name: 'Start' }).click()
  await expect(page.getByTestId('session-timer')).toBeVisible()
}
const phase = (p: Page) => p.getByTestId('session-phase')
const xp = async (p: Page) => (await p.goto('/'), await p.getByTestId('xp-total').textContent())

test('UX-06: Start session opens the plan dialog; Start runs the timer with the card beside it', async ({ page }) => {
  await begin(page)
  await page.getByRole('button', { name: 'Start session' }).click()
  const dlg = page.getByRole('dialog', { name: 'Plan this session' })
  await expect(dlg.getByLabel('This session I will')).toBeVisible()
  for (const name of ['25 / 5', '50 / 10', 'Custom']) await expect(dlg.getByRole('radio', { name })).toBeVisible()
  await dlg.getByLabel('This session I will').fill('trace the queue')
  await dlg.getByRole('button', { name: 'Start' }).click()
  await expect(dlg).toBeHidden()
  await expect(phase(page)).toHaveText('Focus')
  await expect(page.getByTestId('session-timer')).toHaveText(/^2[45]:\d\d$/)
  const brief = page.getByTestId('session-brief')
  await expect(brief).toContainText('Number of Islands')
  await expect(brief).toContainText('This session I will: trace the queue')
  await expect(page.getByTestId('timer-readout')).toHaveText(/^2[45]:\d\d$/)
})

test('UX-07/UX-11: 25/5 cycles, focus-today credits each block, no XP', async ({ page }) => {
  await begin(page)
  const xp0 = await xp(page)
  await expect(page.getByTestId('focus-today')).toHaveText('0 min')
  await page.goto(CARD)
  await startSession(page)
  await page.clock.fastForward('25:00')
  await expect(phase(page)).toHaveText('Break')
  await page.getByRole('dialog', { name: 'Stuck?' }).getByRole('button', { name: "I'm fine" }).click()
  await page.clock.fastForward('05:00')
  await expect(phase(page)).toHaveText('Focus')
  await page.getByRole('textbox', { name: 'Notes' }).fill('x')
  await page.clock.fastForward('25:00')
  await expect(phase(page)).toHaveText('Break')
  expect(await idbAll<{ t: string; minutes?: number }>(page, 'events').then(es => es.filter(e => e.t === 'focus').map(e => e.minutes))).toEqual([25, 25])
  await page.goto('/')
  await expect(page.getByTestId('focus-today')).toHaveText('50 min')
  await expect(page.getByTestId('xp-total')).toHaveText(xp0 as string)
})

test('UX-07: the break after four focus blocks is a Long break', async ({ page }) => {
  await begin(page)
  await startSession(page)
  await page.getByRole('textbox', { name: 'Notes' }).fill('a')
  for (let i = 0; i < 3; i++) {
    await page.clock.fastForward('25:00')
    await expect(phase(page)).toHaveText('Break')
    await page.clock.fastForward('05:00')
    await expect(phase(page)).toHaveText('Focus')
    await page.getByRole('textbox', { name: 'Notes' }).fill(`n${i}`)
  }
  await page.clock.fastForward('25:00')
  await expect(phase(page)).toHaveText('Long break')
  await page.goto('/')
  await expect(page.getByTestId('focus-today')).toHaveText('100 min')
})

test('UX-08: F opens focus mode with only the brief, timer, Notes and two buttons; Esc leaves it and the timer runs on', async ({ page }) => {
  await begin(page)
  await startSession(page, { goal: 'focus test' })
  await page.keyboard.press('f')
  await expect(page.getByRole('button', { name: 'Exit focus mode' })).toBeVisible()
  await expect(page.getByTestId('session-brief')).toBeVisible()
  await expect(page.getByTestId('session-timer')).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Notes' })).toBeVisible()
  const buttons = await page.getByRole('button').evaluateAll(els => els.filter(e => (e as HTMLElement).offsetParent !== null).map(e => e.textContent))
  expect(buttons.sort()).toEqual(['End session', 'Exit focus mode'])
  await expect(page.getByRole('link')).toHaveCount(0)
  await expect(page.getByTestId('ladder')).toBeHidden() // mounted underneath, not visible
  await page.clock.fastForward('01:00')
  const t1 = await page.getByTestId('session-timer').textContent()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('do-back')).toBeVisible()
  await expect(page).toHaveURL(/\/do\/p200$/)
  await page.clock.fastForward('01:00')
  const t2 = await page.getByTestId('session-timer').textContent()
  const secs = (s: string | null) => Number(s!.slice(0, 2)) * 60 + Number(s!.slice(3))
  expect(secs(t1) - secs(t2)).toBeGreaterThanOrEqual(58)
  await page.getByRole('button', { name: 'Focus mode' }).click()
  await expect(page.getByRole('button', { name: 'Exit focus mode' })).toBeVisible()
  await page.getByRole('button', { name: 'Exit focus mode' }).click()
  await expect(page.getByTestId('do-back')).toBeVisible()
})

test('UX-09: a block with no progress raises "Stuck?" once; a typed note suppresses it', async ({ page }) => {
  await begin(page)
  await startSession(page)
  await page.clock.fastForward('25:00')
  const dlg = page.getByRole('dialog', { name: 'Stuck?' })
  await expect(dlg).toBeVisible()
  for (const name of ['Open the next help rung', 'Take a 5-minute break', "I'm fine"]) await expect(dlg.getByRole('button', { name })).toBeVisible()
  await dlg.getByRole('button', { name: "I'm fine" }).click()
  await expect(dlg).toBeHidden()
  await page.clock.fastForward('02:00')
  await expect(dlg).toBeHidden()
  await page.clock.fastForward('03:00')
  await expect(phase(page)).toHaveText('Focus')
  await page.getByRole('textbox', { name: 'Notes' }).fill('made progress')
  await page.clock.fastForward('25:00')
  await expect(phase(page)).toHaveText('Break')
  await expect(dlg).toBeHidden()
})

test('UX-10: End session asks the three fields and Progress shows them', async ({ page }) => {
  await begin(page)
  const xp0 = await xp(page)
  await page.goto(CARD)
  await startSession(page, { goal: 'end log' })
  await page.getByRole('button', { name: 'End session' }).click()
  const dlg = page.getByRole('dialog', { name: 'End session' })
  for (const name of ['Done', 'Stuck on', 'Next step']) await expect(dlg.getByRole('textbox', { name })).toHaveAttribute('maxlength', '280')
  await dlg.getByRole('textbox', { name: 'Done' }).fill('the loop')
  await dlg.getByRole('textbox', { name: 'Stuck on' }).fill('queue order')
  await dlg.getByRole('textbox', { name: 'Next step' }).fill('edge cases')
  await dlg.getByRole('button', { name: 'Save' }).click()
  await expect(dlg).toBeHidden()
  await expect(page.getByTestId('session-timer')).toHaveCount(0)
  const rows = await idbAll<{ outcome: string; xpDelta: number; endLog: unknown }>(page, 'sessions')
  expect(rows).toHaveLength(1)
  expect(rows[0]).toMatchObject({ outcome: 'studied', xpDelta: 0, endLog: { done: 'the loop', stuckOn: 'queue order', nextStep: 'edge cases' } })
  await page.goto('/progress')
  await expect(page.getByTestId('screen-progress')).toHaveAttribute('data-ready', 'true')
  const item = page.locator('[data-testid^="study-session-"]')
  await expect(item).toContainText('Done: the loop')
  await expect(item).toContainText('Stuck on: queue order')
  await expect(item).toContainText('Next step: edge cases')
  await page.reload()
  await expect(page.locator('[data-testid^="study-session-"]')).toContainText('Next step: edge cases')
  expect(await xp(page)).toBe(xp0)
})

test('readability holds in every session state: plan dialog, session panel, focus mode, stuck and end dialogs', async ({ page }) => {
  await begin(page)
  const bad = async (label: string) => {
    const els = await ownTextElements(page)
    const tiny = els.filter(e => e.size < 14).map(e => `${e.tag}.${e.cls} "${e.text}" ${e.size}px`)
    const pixel = els.filter(e => /^"?Silkscreen/.test(e.family) && ![16, 24, 32, 48].includes(e.size)).map(e => `${e.tag}.${e.cls} ${e.size}px`)
    expect([label, tiny, pixel]).toEqual([label, [], []])
  }
  await page.getByRole('button', { name: 'Start session' }).click()
  await bad('plan dialog')
  await page.getByRole('radio', { name: 'Custom' }).check()
  await bad('plan dialog custom')
  await page.getByRole('dialog', { name: 'Plan this session' }).getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.getByTestId('session-timer')).toBeVisible()
  await bad('session panel')
  // ui-do D4 / ruling 10: the ladder's rung notes are Chivo 15 secondary descriptions, not reading paragraphs
  const ps = (await ownTextElements(page)).filter(e => e.tag === 'p' && e.cls !== 'rung-note')
  for (const p of ps) expect([p.cls, /^"?Chivo/.test(p.family), p.size >= 17, p.lh >= 1.5 * p.size - 0.01]).toEqual([p.cls, true, true, true])
  await page.keyboard.press('f')
  await bad('focus mode')
  await page.keyboard.press('Escape')
  await page.clock.fastForward('25:00')
  await expect(page.getByRole('dialog', { name: 'Stuck?' })).toBeVisible()
  await bad('stuck dialog')
  await page.getByRole('button', { name: "I'm fine" }).click()
  await page.getByRole('button', { name: 'End session' }).click()
  await bad('end dialog')
})

test('UX-12: the session runs on every screen: focus-today reads 25 min without returning to Do', async ({ page }) => {
  await begin(page)
  await startSession(page)
  await page.getByRole('textbox', { name: 'Notes' }).fill('some progress')
  await page.goto('/')
  await expect(page.getByTestId('focus-today')).toHaveText('0 min')
  await page.clock.fastForward('25:00')
  await expect(page.getByTestId('focus-today')).toHaveText('25 min')
  await page.clock.fastForward('05:00')
  await page.clock.fastForward('25:00')
  await expect(page.getByTestId('focus-today')).toHaveText('50 min')
})

test('UX-13: two tabs on one session credit a block once; after one ends it the other never brings it back', async ({ context, page }) => {
  await begin(page)
  await startSession(page)
  await page.getByRole('textbox', { name: 'Notes' }).fill('n')
  const other = await context.newPage() // same context: same clock, same storage, same locks
  await other.goto('/')
  await expect(other.getByTestId('focus-today')).toHaveText('0 min')
  await page.clock.fastForward('25:05')
  await expect(other.getByTestId('focus-today')).toHaveText('25 min')
  expect(await idbAll<{ t: string }>(page, 'events').then(es => es.filter(e => e.t === 'focus').length)).toBe(1)
  await page.getByRole('button', { name: 'End session' }).click()
  await page.getByRole('dialog', { name: 'End session' }).getByRole('button', { name: 'Save' }).click()
  await expect(page.getByTestId('session-timer')).toHaveCount(0)
  await page.clock.fastForward('30:00')
  await other.reload()
  await expect(other.getByTestId('focus-today')).toHaveText('25 min')
  expect(await idbAll<{ outcome: string }>(page, 'sessions').then(s => s.filter(x => x.outcome === 'studied').length)).toBe(1)
  expect(await other.evaluate(() => localStorage.getItem('dojo-study'))).toBeNull()
})

test('UX-14: a sleep gap credits the running block then parks the session behind "Welcome back"', async ({ page }) => {
  await begin(page)
  await startSession(page)
  await page.getByRole('textbox', { name: 'Notes' }).fill('n')
  await page.clock.fastForward('05:00:00')
  const dlg = page.getByRole('dialog', { name: 'Welcome back' })
  await expect(dlg).toContainText('You were away: Resume or End?')
  await expect(dlg.getByRole('button', { name: 'Resume' })).toBeVisible()
  expect(await idbAll<{ t: string; minutes?: number }>(page, 'events').then(es => es.filter(e => e.t === 'focus').map(e => e.minutes))).toEqual([25])
  await page.clock.fastForward('01:00:00')
  expect(await idbAll<{ t: string }>(page, 'events').then(es => es.filter(e => e.t === 'focus').length)).toBe(1)
  await dlg.getByRole('button', { name: 'End' }).click()
  await page.getByRole('dialog', { name: 'End session' }).getByRole('button', { name: 'Save' }).click()
  await expect(dlg).toBeHidden()
  await expect.poll(async () => (await idbAll<{ outcome: string }>(page, 'sessions')).filter(s => s.outcome === 'studied').length).toBe(1)
})

test('UX-17: Stuck? opens with focus on "I\'m fine"; the next help rung leaves focus mode and shows the rung', async ({ page }) => {
  await begin(page)
  await startSession(page)
  await page.keyboard.press('f')
  await expect(page.getByRole('textbox', { name: 'Notes' })).toBeFocused()
  await page.clock.fastForward('25:00')
  const dlg = page.getByRole('dialog', { name: 'Stuck?' })
  await expect(dlg.getByRole('button', { name: "I'm fine" })).toBeFocused()
  await dlg.getByRole('button', { name: 'Open the next help rung' }).click()
  await expect(page.getByRole('button', { name: 'Exit focus mode' })).toHaveCount(0)
  await expect(page.getByTestId('ladder-rung-hint')).toBeVisible()
  await expect(page.getByTestId('ladder-rung-hint')).toHaveAttribute('data-state', 'open')
})
