// Code generated by the Dojo runner. DO NOT EDIT.
// The runner overwrites this file in each run's module (runner.mjs wireLimits). This checked-in copy
// has no progPath, so a binary built from it refuses to start.

package wire

const (
	maxMem        uint64 = 536870912
	maxGoroutines        = 10000
	maxFileBytes  uint64 = 68157440
	cpuSoft       uint64 = 4
	cpuHard       uint64 = 5
	wallGuardMs          = 4000
	progPath             = ""
)
