// Package wire is the Dojo harness's link to the runner. Its init (start, in init.go) runs before any
// code in package main (the learner's file), because every imported package is initialised before
// main's own init functions and package variables. It:
//
//   - removes the program's own binary (progPath). The sandbox lets the program unlink that one path
//     but never create, replace or link it, so the program cannot exec itself again (security round 2
//     M-A: a re-exec with the learner's own pipe on fd 5 used to start a fresh instance), and a second
//     instance, should one ever start, finds the binary gone and refuses to run;
//   - reads the run's key from fd 5 (one line: 48 lowercase hex digits) and closes fd 5. fd 5 carries
//     the key only: the limits are build constants (limits.go, generated by the runner for each run),
//     so nothing the learner can put on fd 5 changes them. A missing or malformed key stops the
//     program before the learner's code runs;
//   - applies the limits the learner must not be able to lift: RLIMIT_NOFILE and RLIMIT_FSIZE (soft
//     and hard, so they cannot be raised again), the OS-thread cap and the stack cap;
//   - starts the watchdog that stops the program past the memory or goroutine cap;
//   - R5: makes the program limit itself even if the runner loses it (a server SIGKILLed mid-run left a
//     CPU loop running for 7 hours, its session leader reparented to launchd): RLIMIT_CPU (soft
//     cpuSoft s, hard cpuHard s), a guard that exits once the CPU used reaches cpuSoft s (macOS only
//     ever sends SIGXCPU, even past the hard limit, and Go's runtime ignores it; os/signal is not used
//     because on darwin it opens a pipe, which would take the fd 5 just closed), a wall guard at
//     wallGuardMs (the runner's wall limit plus a grace) that does not depend on the parent, and an exit
//     as soon as getppid() is 1 (the runner is gone).
//
// Every line written to the runner (results on fd 4, events on fd 3) starts with the key; the runner
// drops lines without it, so the learner cannot forge results or events by writing to those fds.
// Being internal to dojo/tk, this package cannot be imported from package main, and the runner
// refuses //go:linkname.
package wire

import (
	"os"
	"runtime"
	"runtime/debug"
	"runtime/metrics"
	"syscall"
	"time"
)

const (
	// MaxFiles is the open-file cap (RLIMIT_NOFILE).
	MaxFiles = 256
	// MaxThreads is the OS-thread cap.
	MaxThreads = 256
	// MaxStack is the per-goroutine stack cap (deep recursion is a "stack overflow").
	MaxStack = 64 << 20
	// KeyLen is the run key's length: 24 random bytes in lowercase hex.
	KeyLen = 48
)

var (
	key     []byte
	results = os.NewFile(4, "dojo-results")
)

// start is the package's init (see init.go). Nothing the learner wrote has run yet.
func start() {
	if progPath == "" || os.Remove(progPath) != nil {
		refuse("this program was started twice")
	}
	if !readKey() {
		refuse("the run key on fd 5 is missing or malformed")
	}
	for _, l := range []struct {
		res int
		n   uint64
	}{{syscall.RLIMIT_NOFILE, MaxFiles}, {syscall.RLIMIT_FSIZE, maxFileBytes}} {
		lim := syscall.Rlimit{Cur: l.n, Max: l.n}
		syscall.Setrlimit(l.res, &lim)
	}
	cpu := syscall.Rlimit{Cur: cpuSoft, Max: cpuHard}
	syscall.Setrlimit(syscall.RLIMIT_CPU, &cpu)
	debug.SetMaxThreads(MaxThreads)
	debug.SetMaxStack(MaxStack)
	go watch()
	go guard()
}

// refuse stops a program the runner did not start as it expects, before any learner code runs.
func refuse(why string) {
	os.Stderr.WriteString("dojo: " + why + ": only the Dojo runner may start this program\n")
	os.Exit(4)
}

// readKey reads the key line from fd 5 into a fixed buffer, keeps only the key bytes, and zeroes the
// buffer (security round 2 M-C: no stray copy of the key line stays in memory; the key itself must).
func readKey() bool {
	f := os.NewFile(5, "dojo-key")
	if f == nil {
		return false
	}
	var buf [KeyLen + 2]byte
	n := 0
	for n < len(buf) {
		m, err := f.Read(buf[n:])
		if m > 0 {
			n += m
		}
		if err != nil || (n > 0 && buf[n-1] == '\n') {
			break
		}
	}
	f.Close()
	k, ok := ParseKey(buf[:n])
	clear(buf[:])
	if ok {
		key = k
	}
	return ok
}

// ParseKey returns the key in line ("<48 lowercase hex digits>\n" and nothing else) as a new slice,
// and zeroes line whatever it holds.
func ParseKey(line []byte) ([]byte, bool) {
	defer clear(line)
	if len(line) != KeyLen+1 || line[KeyLen] != '\n' {
		return nil, false
	}
	for _, c := range line[:KeyLen] {
		if !('0' <= c && c <= '9' || 'a' <= c && c <= 'f') {
			return nil, false
		}
	}
	k := make([]byte, KeyLen)
	copy(k, line[:KeyLen])
	return k, true
}

// Frame appends the line prefix (the key and a space) to buf.
func Frame(buf []byte) []byte {
	buf = append(buf, key...)
	return append(buf, ' ')
}

// Result writes one framed line to the runner's results pipe (fd 4).
func Result(s string) {
	b := Frame(make([]byte, 0, len(s)+len(key)+2))
	b = append(b, s...)
	b = append(b, '\n')
	results.Write(b)
	clear(b[:len(key)]) // no copy of the key is left behind in the line buffer (M-C)
}

// OverMemory reports whether the Go runtime has mapped more than the memory cap (this catches an
// allocation before its pages are touched, which the runner's RSS poll cannot see).
func OverMemory() bool {
	s := []metrics.Sample{{Name: "/memory/classes/total:bytes"}}
	metrics.Read(s)
	return s[0].Value.Kind() == metrics.KindUint64 && s[0].Value.Uint64() > maxMem
}

// Stop reports a limit to the runner and exits.
func Stop(what string) {
	Result(`{"limit":"` + what + `"}`)
	os.Exit(3)
}

// guard is R5's parent-independent stop: the CPU budget, the wall guard, and the parent's death. Each
// reports a limit line (the runner reads "cpu" and "wall" as a timeout) and exits.
func guard() {
	wall := time.NewTimer(time.Duration(wallGuardMs) * time.Millisecond)
	tick := time.NewTicker(50 * time.Millisecond)
	for {
		select {
		case <-wall.C:
			Stop("wall")
		case <-tick.C:
			if os.Getppid() == 1 {
				Stop("orphaned")
			}
			if cpuUsed() >= time.Duration(cpuSoft)*time.Second {
				Stop("cpu")
			}
		}
	}
}

// cpuUsed is the CPU time (user and system, every thread) the program has used so far.
func cpuUsed() time.Duration {
	var ru syscall.Rusage
	if syscall.Getrusage(syscall.RUSAGE_SELF, &ru) != nil {
		return 0
	}
	return time.Duration(ru.Utime.Nano() + ru.Stime.Nano())
}

func watch() {
	for {
		if OverMemory() {
			Stop("memory")
		}
		if runtime.NumGoroutine() > maxGoroutines {
			Stop("goroutines")
		}
		time.Sleep(5 * time.Millisecond)
	}
}
