// Copies the prototype's frozen engines into public/engines (BUILD.md "Engines as-is").
// sr/: charts.js (as-is) and pom-stage.js (the only edit: load the vendored three.js instead of unpkg).
// lab/: diagram.js, algo.js and algo2.js (the append-only pack) byte-for-byte except the
// ENGINE_PATCHES below (SEC-D-01). Each is a self-contained IIFE with no imports, so there is nothing else to vendor.
// atlas-pieces.js (labs chain): wraps the Atlas prototype's logic block (verbatim) so its 17
// walkthroughs and pattern map run outside the prototype runtime (support.js is not ported).
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const HANDOFF = resolve(here, '../design_handoff_quest_dashboard')
const SRC = resolve(HANDOFF, 'sr')
const LAB = resolve(HANDOFF, 'lab')
const OUT = resolve(here, '../public/engines')
const CDN_THREE = "const THREE_URL = 'https://unpkg.com/three@0.184.0/build/three.module.js';"
const LOCAL_THREE = "const THREE_URL = '/engines/vendor/three/three.module.min.js';"

export const ATLAS_OPEN = '<script type="text/x-dc" data-dc-script>\n'
export const ATLAS_HEAD = [
  '// atlas-pieces.js: GENERATED by scripts/vendor-engines.mjs. Do not edit.',
  '// Source: design_handoff_quest_dashboard/lab/Algorithm Atlas.dc.html, the <script data-dc-script> block, verbatim',
  '// between the BEGIN/END markers. It exposes the block\'s renderVals() result as window.SRAtlas.',
  '(() => {',
  '  if (window.SRAtlas) return;',
  '  class DCLogic {}',
  '// ---- BEGIN VERBATIM ----',
].join('\n')
export const ATLAS_TAIL = [
  '// ---- END VERBATIM ----',
  '  window.SRAtlas = new Component().renderVals();',
  '})();',
  '',
].join('\n')

// SEC-D-01 (G6 security review): the engines interpolated picture text (title, complexity, the load error
// and each step's vars) into innerHTML, so an AI or stored picture could run script in the writer's window.
// These are the only deviations from the handoff: the same nodes, filled with textContent instead.
const ERROR_HTML = 'e.innerHTML = `<div class="say" style="color:${T.danger}">NO ALGORITHM · ${d && d.error ? d.error : \'give structures + steps\'}</div>`;'
const ERROR_TEXT = 'e.innerHTML = `<div class="say" style="color:${T.danger}"></div>`; e.firstChild.textContent = `NO ALGORITHM · ${d && d.error ? d.error : \'give structures + steps\'}`;'
const HEAD_HTML = '<span class="title">${(d.title || \'ALGORITHM\').toUpperCase()}</span><span class="badge">${d.complexity || \'\'}</span>'
const HEAD_EMPTY = '<span class="title"></span><span class="badge"></span>'
const HEAD_TEXT = ' wrap.querySelector(\'.title\').textContent = (d.title || \'ALGORITHM\').toUpperCase(); wrap.querySelector(\'.badge\').textContent = `${d.complexity || \'\'}`;'
const ALGO_BAR_END = '<option value="4">4×</option></select></div>`;'
const ALGO2_BAR_END = '<span class="count"></span><div class="scrub"></div></div>`;'
const VARS_B = 'const b = document.createElement(\'b\'); b.textContent = k; '

// UAT cu-5 P3-11 (the one deviation that is not SEC-D-01): an array's drawing is 14 px taller while any pointer is set, so the
// structure under it (the DP row in a picture) jumped down when the first pointer appeared and back when it went. A structure
// that is pointed at anywhere in the walk now keeps that room from the first step.
const ARRAY_HEIGHT = 'return 30 + CH + 22 + (ptrs.length ? 14 : 0); };'
const ARRAY_HEIGHT_HELD = 'return 30 + CH + 22 + (ptrs.length || t.holdPtr ? 14 : 0); };'
const DRAW_LOOP = 'for (const name in s) { const t = s[name]; const fn = DRAW[t.type]; if (!fn) continue; y += fn(g, t, t.title || name, 4, y, W, T) + 10; }'
const DRAW_LOOP_HELD = 'for (const name in s) { const t = s[name]; const fn = DRAW[t.type]; if (!fn) continue; t.holdPtr = (d.steps || []).some(q => q.op === \'pointer\' && (q.s || q.g || q.on) === name); y += fn(g, t, t.title || name, 4, y, W, T) + 10; }'
// UAT cu-6 P2-1 / P3-3: the engines drew every graph node 26 px wide, every array / queue / list cell 20-32 px and every
// caption in one unwrapped line, so a node named `shirt`, an ORDER cell `jacket` or the union-find caption ran past its
// box. Text width is estimated per character (Silkscreen about 1 em, Space Mono 0.8 em as drawn, both conservative), the box grows
// to the text, and a caption wider than its pane is squeezed (or, when that would be too much, cut with a hover title).
const TEXT_FIT = [
  "const GW = (s, size, mono) => String(s).length * size * (mono ? 0.8 : 1);",
  "const fitCaptions = (svg, W) => svg.querySelectorAll('text[data-cap]').forEach(tx => { try {",
  "const room = W - 4 - Number(tx.getAttribute('x')); const len = tx.getComputedTextLength(); if (!(len > room)) return;",
  "if (room / len >= .75) { tx.setAttribute('textLength', Math.floor(room)); tx.setAttribute('lengthAdjust', 'spacingAndGlyphs'); return; }",
  "const full = tx.textContent; tx.textContent = full.slice(0, Math.max(3, Math.floor(full.length * room / len) - 1)).trimEnd() + '…'; tx.appendChild(el('title', {}, full));",
  "} catch (e) { } });",
].join(' ')
const CAP_FIT = '{ const tx = TXT(x, y, s.toUpperCase(), { fill: T.text2 }); tx.setAttribute(\'data-cap\', \'\'); g.appendChild(tx); };'
const DRAW_FIT = "stage.innerHTML = ''; stage.appendChild(svg); fitCaptions(svg, W);"

// UAT cu-final row 25: the app's readable-type sheet (lib/engineType.ts) draws every engine text at 14 px, but the diagram engine
// sizes a node chip and spaces its label and sub-label for 9 px text. So "API GATEWAY" sat on "auth, rate limit" and a long label
// or sub-label ran past the chip. The chip now measures 14 px text (a per-character floor for before fonts load), the sub-label
// line sits 18 px under the label line (it was 11), and a link label's plate is sized for 14 px too.
const DIAGRAM_LAYOUT_FROM = `nodes.forEach(n => { n.h = NH + (n.sub ? 10 : 0) + (n.fields ? n.fields.length * 12 + 4 : 0); const lw = 28 + Math.max(measure((n.label || n.id).toUpperCase(), '700 9px Silkscreen, monospace', 8.2), measure(n.sub || '', '9px "Space Mono", monospace', 6)) + 12;`
const DIAGRAM_LAYOUT_TO = `nodes.forEach(n => { n.h = NH + (n.sub ? 18 : 0) + (n.fields ? n.fields.length * 12 + 4 : 0); const lab = (n.label || n.id).toUpperCase(), sb = n.sub || ''; const lw = 28 + Math.max(measure(lab, '700 14px "Space Mono", monospace', 9.4), lab.length * 9.4, measure(sb, '14px "Space Mono", monospace', 8.8), sb.length * 8.8) + 12;`
const DIAGRAM_TEXT_FROM = `ng.appendChild(TXT(n.px + 28, chipY + 17, (n.label || n.id).toUpperCase(), { fill: T.text, bold: true })); if (n.sub) ng.appendChild(TXT(n.px + 28, chipY + 28, n.sub, { fill: T.text2, mono: true, size: 9 }));`
const DIAGRAM_TEXT_TO = `ng.appendChild(TXT(n.px + 28, chipY + 19, (n.label || n.id).toUpperCase(), { fill: T.text, bold: true })); if (n.sub) ng.appendChild(TXT(n.px + 28, chipY + 37, n.sub, { fill: T.text2, mono: true, size: 9 }));`
const DIAGRAM_FIELDS_FROM = `const y = n.py + PROP_H + 30 + (n.sub ? 10 : 0) + i * 12;`
const DIAGRAM_FIELDS_TO = `const y = n.py + PROP_H + 30 + (n.sub ? 18 : 0) + i * 12;`

// A layered column also starts after the widest node of the column before it (the stride was a fixed NW + GX, which the wider chips overran).
const DIAGRAM_COL_FROM = `Object.entries(cols).forEach(([r, list]) => { const tot = list.reduce((a, n) => a + n.h + GY, 0); let y = PAD + Math.round((maxN - tot) / 2 / GRID) * GRID; list.forEach(n => { n.px = PAD + r * (NW + GX); n.py = y; y += n.h + GY; }); });`
const DIAGRAM_COL_TO = `const colX = {}; { let cx = PAD; Object.keys(cols).map(Number).sort((a, b) => a - b).forEach(r => { colX[r] = cx; cx += Math.max(NW, ...cols[r].map(n => n.w)) + GX; }); }
      Object.entries(cols).forEach(([r, list]) => { const tot = list.reduce((a, n) => a + n.h + GY, 0); let y = PAD + Math.round((maxN - tot) / 2 / GRID) * GRID; list.forEach(n => { n.px = colX[r]; n.py = y; y += n.h + GY; }); });`

/** [from, to] replacements per engine file; each `from` must occur exactly once in the handoff source. */
export const ENGINE_PATCHES = {
  'diagram.js': [
    [DIAGRAM_LAYOUT_FROM, DIAGRAM_LAYOUT_TO],
    [DIAGRAM_TEXT_FROM, DIAGRAM_TEXT_TO],
    [DIAGRAM_FIELDS_FROM, DIAGRAM_FIELDS_TO],
    [DIAGRAM_COL_FROM, DIAGRAM_COL_TO],
  ],
  'algo.js': [
    [ERROR_HTML, ERROR_TEXT],
    [HEAD_HTML, HEAD_EMPTY],
    [ALGO_BAR_END, ALGO_BAR_END + HEAD_TEXT],
    ['sp.innerHTML = `<b>${k}</b>${fmt(v)}`;', VARS_B + 'sp.append(b, fmt(v));'],
    [ARRAY_HEIGHT, ARRAY_HEIGHT_HELD],
    [DRAW_LOOP, DRAW_LOOP_HELD],
    // cu-6 P2-1: boxes grow to their text
    ['const NW = 26;', 'const NW = 26; const NWo = id => Math.max(NW, Math.ceil(GW(t.nodes[id].label || id, 9)) + 10);'],
    ['(x2 > mx ? -NW / 2 : NW / 2)', '(x2 > mx ? -NWo(v) / 2 : NWo(v) / 2)'],
    ['bevelCell(g, x0 + x - NW / 2, top + y - NW / 2, NW, NW, state ? cellFill(T, state) : T.panel, T);', 'bevelCell(g, x0 + x - NWo(id) / 2, top + y - NW / 2, NWo(id), NW, state ? cellFill(T, state) : T.panel, T);'],
    [
      'const CW = Math.max(20, Math.min(32, Math.floor((W - 8) / Math.max(1, n)) - 2)), CH = 28;',
      'const CW = Math.max(20, Math.min(32, Math.floor((W - 8) / Math.max(1, n)) - 2), ...t.values.map(v => Math.ceil(GW(fmt(v), String(fmt(v)).length > 3 ? 9 : 11, true)) + 8)), CH = 28;',
    ],
    ['const top = y0 + 30, CW = 30, CH = 26;', 'const top = y0 + 30, CW = Math.max(30, ...t.values.map(v => Math.ceil(GW(fmt(v), 11, true)) + 8)), CH = 26;'],
    ['const top = y0 + 30, CW = 30, GAP = 26;', 'const top = y0 + 30, CW = Math.max(30, ...t.values.map(v => Math.ceil(GW(fmt(v), 11, true)) + 8)), GAP = 26;'],
    ['const CW = 64, CH = 22;', 'const CW = Math.max(64, ...t.values.map(v => Math.ceil(GW(fmt(v), 11, true)) + 8)), CH = 22;'],
    // cu-6 P3-3: a caption wider than its pane is fitted
    ['const caption = (g, x, y, s, T) => g.appendChild(TXT(x, y, s.toUpperCase(), { fill: T.text2 }));', 'const caption = (g, x, y, s, T) => ' + CAP_FIT + ' ' + TEXT_FIT],
    ["stage.innerHTML = ''; stage.appendChild(svg);", DRAW_FIT],
  ],
  'algo2.js': [
    [ERROR_HTML, ERROR_TEXT],
    [HEAD_HTML, HEAD_EMPTY],
    [ALGO2_BAR_END, ALGO2_BAR_END + HEAD_TEXT],
    ['sp.innerHTML = `<b>${k}</b>${st.vars[k]}`;', VARS_B + 'sp.append(b, `${st.vars[k]}`);'],
    // cu-6 P3-3: the caption is fitted, and the union-find forest keeps its pointer tag above its node (not beside it, over
    // the neighbour's rank tag), with a row of room above the roots and between the levels for it
    ['const cap = (g, x, y, s, T) => g.appendChild(TXT(x, y, s.toUpperCase(), { fill: T.text2 }));', 'const cap = (g, x, y, s, T) => ' + CAP_FIT + ' ' + TEXT_FIT],
    ["stage.innerHTML = ''; stage.appendChild(svg);", DRAW_FIT],
    ['const NW = 26, top = y0 + 24;', 'const NW = 26, top = y0 + 50;'],
    ['top + d * 44 + NW / 2', 'top + d * 58 + NW / 2'],
    ['const ay = top + (maxD + 1) * 44 + 6;', 'const ay = top + (maxD + 1) * 58 + 6;'],
    [
      'arrow(g, x + NW / 2 + 8, y + 4, c); g.appendChild(TXT(x + NW / 2 + 14, y - 8, nm, { fill: c }));',
      'arrow(g, x + NW / 2 + 8, y + 4, c); { const w = Math.ceil(GW(nm, 9)); const tx = Math.min(Math.max(x, x0 + w / 2 + 2), x0 + W - 8 - w / 2); g.appendChild(R(tx - w / 2 - 2, y - NW / 2 - 31, w + 4, 11, T.well)); g.appendChild(TXT(tx, y - NW / 2 - 22, nm, { anchor: \'middle\', fill: c })); }',
    ],
  ],
}

/** The handoff engine source with its ENGINE_PATCHES applied (unchanged for an engine without patches). */
export function patchEngine(name, src) {
  let out = src
  for (const [from, to] of ENGINE_PATCHES[name] ?? []) {
    const n = out.split(from).length - 1
    if (n !== 1) throw new Error(`${name}: SEC-D-01 patch site found ${n} times (expected 1): ${from.slice(0, 80)}`)
    out = out.replace(from, () => to)
  }
  return out
}

/** The prototype's logic block, byte for byte (between the opening tag's newline and `</script>`). */
export function atlasBlock(html) {
  const start = html.indexOf(ATLAS_OPEN)
  if (start < 0) throw new Error('Algorithm Atlas: data-dc-script block not found')
  const from = start + ATLAS_OPEN.length
  const end = html.indexOf('</script>', from)
  if (end < 0) throw new Error('Algorithm Atlas: data-dc-script block is not closed')
  return html.slice(from, end)
}

function main() {
  if (!existsSync(HANDOFF)) {
    console.log('engines: the design prototypes (design_handoff_quest_dashboard/) are not in this repository; nothing to vendor. public/engines/ is the source of truth here.')
    return
  }
  mkdirSync(OUT, { recursive: true })
  copyFileSync(resolve(SRC, 'charts.js'), resolve(OUT, 'charts.js'))
  for (const f of ['diagram.js', 'algo.js', 'algo2.js']) writeFileSync(resolve(OUT, f), patchEngine(f, readFileSync(resolve(LAB, f), 'utf8')))
  const pom = readFileSync(resolve(SRC, 'pom-stage.js'), 'utf8')
  if (pom.split(CDN_THREE).length !== 2) throw new Error('pom-stage.js: expected exactly one THREE_URL line to rewrite')
  writeFileSync(resolve(OUT, 'pom-stage.js'), pom.replace(CDN_THREE, LOCAL_THREE))
  const atlas = readFileSync(resolve(LAB, 'Algorithm Atlas.dc.html'), 'utf8')
  writeFileSync(resolve(OUT, 'atlas-pieces.js'), `${ATLAS_HEAD}\n${atlasBlock(atlas)}${ATLAS_TAIL}`)
  console.log('engines vendored into public/engines')
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
