import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import type { ArtifactRecord } from '../../src/rules/artifacts'
import { addUserArtifact, projectDb, REPO, renderAi } from '../helpers/projects'

const cardOf = (title: string) =>
  screen.queryAllByTestId('board-card').find(c => within(c).getByTestId('board-card-open').textContent === title) ?? null
const change = (el: HTMLElement, value: string) => fireEvent.change(el, { target: { value } })

describe('Artifact dialog (C-PROJECTS §2.5)', () => {
  it('makes the rest of the app inert while open, and live again once closed (Dialog.tsx)', async () => {
    await renderAi()
    const rest = ([...document.body.children] as HTMLElement[]).filter(el => !el.hasAttribute('data-live-region'))
    expect(rest.length).toBeGreaterThan(0)
    rest.forEach(el => expect(el.inert).toBeFalsy())
    fireEvent.click(screen.getByRole('button', { name: 'Add artifact' }))
    const dlg = screen.getByRole('dialog', { name: 'New artifact' })
    rest.forEach(el => expect(el.inert).toBe(true))
    fireEvent.click(within(dlg).getByRole('button', { name: 'Cancel' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    rest.forEach(el => expect(el.inert).toBeFalsy())
  })

  it('Add artifact → New artifact → Save creates the card (scenario 4)', async () => {
    await renderAi()
    fireEvent.click(screen.getByRole('button', { name: 'Add artifact' }))
    const dlg = screen.getByRole('dialog', { name: 'New artifact' })
    expect(dlg).toHaveAttribute('data-testid', 'artifact-dialog')
    expect(document.activeElement).toBe(within(dlg).getByLabelText('Title'))
    change(within(dlg).getByLabelText('Title'), 'micrograd engine')
    change(within(dlg).getByLabelText('Stage'), '1')
    change(within(dlg).getByLabelText('Repo URL'), REPO)
    change(within(dlg).getByLabelText('Commit'), 'a1b2c3d')
    expect(within(dlg).queryByTestId('artifact-delete')).toBeNull()
    fireEvent.click(within(dlg).getByRole('button', { name: 'Save' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    await waitFor(() => expect(cardOf('micrograd engine')).toHaveAttribute('data-stage', '01'))
    expect(screen.getByTestId('ai-evidence-measured')).toHaveTextContent('0/13')
    expect(document.activeElement).toBe(screen.getByRole('button', { name: 'Add artifact' }))
  })

  it('shows each field error and Save creates nothing while any shows (scenario 5)', async () => {
    const d = await renderAi()
    fireEvent.click(screen.getByRole('button', { name: 'Add artifact' }))
    const dlg = screen.getByRole('dialog', { name: 'New artifact' })
    expect(within(dlg).queryByText('Title is required.')).toBeNull()
    change(within(dlg).getByLabelText('Repo URL'), 'github.com/x')
    expect(within(dlg).getByText('Enter an http(s) URL.')).toBeInTheDocument()
    change(within(dlg).getByLabelText('Commit'), 'xyz123')
    expect(within(dlg).getByText('A commit is 7–40 hex characters.')).toBeInTheDocument()
    change(within(dlg).getByLabelText('Write-up link'), 'notes/foo.txt')
    expect(within(dlg).getByText('Use an obsidian:// link, a URL, or a .md path.')).toBeInTheDocument()
    fireEvent.click(within(dlg).getByRole('button', { name: 'Save' }))
    expect(within(dlg).getByText('Title is required.')).toBeInTheDocument()
    expect(screen.getByRole('dialog', { name: 'New artifact' })).toBeInTheDocument()
    expect(await d.artifacts.count()).toBe(12)
  })

  it('deep link opens the saved values; Esc closes, drops the param and refocuses the card (scenario 6)', async () => {
    const d = await projectDb()
    const id = await addUserArtifact(d, { title: 'micrograd engine', stage: 1, repo: REPO, commit: 'a1b2c3d' })
    await renderAi({ db: d, route: `/ai?artifact=${id}` })
    const dlg = await screen.findByRole('dialog', { name: 'Artifact · micrograd engine' })
    expect(within(dlg).getByLabelText('Title')).toHaveValue('micrograd engine')
    expect(within(dlg).getByLabelText('Repo URL')).toHaveValue(REPO)
    expect(within(dlg).getByLabelText('Commit')).toHaveValue('a1b2c3d')
    expect(within(dlg).getByLabelText('Stage')).toHaveValue('1')
    expect(within(dlg).getByTestId('artifact-commit-checked')).toHaveTextContent('Commit not checked yet')
    fireEvent.keyDown(dlg, { key: 'Escape' })
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    expect(screen.getByTestId('location')).toHaveAttribute('data-search', '')
    expect(document.activeElement).toBe(within(cardOf('micrograd engine') as HTMLElement).getByTestId('board-card-open'))
  })

  it('a card open button opens its dialog; Cancel discards edits', async () => {
    const d = await renderAi()
    fireEvent.click(within(cardOf('Stage 04 · Tokenizer (BPE)') as HTMLElement).getByTestId('board-card-open'))
    const dlg = await screen.findByRole('dialog', { name: 'Artifact · Stage 04 · Tokenizer (BPE)' })
    change(within(dlg).getByLabelText('Title'), 'renamed')
    fireEvent.click(within(dlg).getByRole('button', { name: 'Cancel' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    expect(((await d.artifacts.get('art-stage-04')) as ArtifactRecord).title).toBe('Stage 04 · Tokenizer (BPE)')
  })

  it('an unknown or deleted id renders the page and no dialog (Review Focus #3)', async () => {
    await renderAi({ route: '/ai?artifact=nope' })
    expect(screen.getByRole('region', { name: 'Build board' })).toBeInTheDocument()
    expect(screen.queryByRole('dialog')).toBeNull()
  })

  it('the Status select applies the same gates and keeps the previous status (scenario 15)', async () => {
    const d = await projectDb()
    const id = await addUserArtifact(d, { title: 'micrograd engine', stage: 1 })
    await renderAi({ db: d, route: `/ai?artifact=${id}` })
    const dlg = await screen.findByRole('dialog', { name: 'Artifact · micrograd engine' })
    change(within(dlg).getByLabelText('Status'), 'runs')
    expect(within(dlg).getByRole('alert')).toHaveTextContent('Runs needs a repo URL and a commit.')
    expect(within(dlg).getByLabelText('Status')).toHaveValue('not started')
    change(within(dlg).getByLabelText('Repo URL'), REPO)
    change(within(dlg).getByLabelText('Commit'), 'a1b2c3d')
    change(within(dlg).getByLabelText('Status'), 'runs')
    expect(within(dlg).queryByRole('alert')).toBeNull()
    fireEvent.click(within(dlg).getByRole('button', { name: 'Save' }))
    await waitFor(() => expect(cardOf('micrograd engine')).toHaveAttribute('data-status', 'runs'))
  })

  it('saving a changed commit clears Commit checked and Done (Review Focus #1)', async () => {
    const d = await projectDb()
    await d.artifacts.update('art-stage-00', { repo: REPO, commit: 'c0ffee1', commitFound: true, grade: 4 })
    await renderAi({ db: d, route: '/ai?artifact=art-stage-00' })
    const dlg = await screen.findByRole('dialog', { name: 'Artifact · Stage 00 · Setup + math by picture' })
    expect(within(dlg).getByTestId('artifact-done')).toHaveTextContent('Done')
    expect(within(dlg).getByTestId('artifact-commit-checked')).toHaveTextContent('Commit checked')
    change(within(dlg).getByLabelText('Commit'), 'b4c5d6e7')
    fireEvent.click(within(dlg).getByRole('button', { name: 'Save' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    const a = (await d.artifacts.get('art-stage-00')) as ArtifactRecord
    expect(a.commitFound).toBeUndefined()
    expect(a.grade).toBe(4)
    expect(within(cardOf('Stage 00 · Setup + math by picture') as HTMLElement).queryByTestId('artifact-done-badge')).toBeNull()
  })

  it('Delete artifact asks first; Keep keeps, Delete removes; seeded artifacts have no Delete (scenario 7)', async () => {
    const d = await projectDb()
    const id = await addUserArtifact(d, { title: 'micrograd engine', stage: 1 })
    await renderAi({ db: d, route: `/ai?artifact=${id}` })
    let dlg = await screen.findByRole('dialog', { name: 'Artifact · micrograd engine' })
    fireEvent.click(within(dlg).getByRole('button', { name: 'Delete artifact' }))
    const confirm = screen.getByRole('alertdialog')
    expect(document.activeElement).toBe(within(confirm).getByRole('button', { name: 'Keep' }))
    fireEvent.click(within(confirm).getByRole('button', { name: 'Keep' }))
    expect(screen.queryByRole('alertdialog')).toBeNull()
    expect(await d.artifacts.get(id)).toBeTruthy()
    dlg = screen.getByRole('dialog', { name: 'Artifact · micrograd engine' })
    fireEvent.click(within(dlg).getByRole('button', { name: 'Delete artifact' }))
    fireEvent.click(within(screen.getByRole('alertdialog')).getByRole('button', { name: 'Delete' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    await waitFor(() => expect(cardOf('micrograd engine')).toBeNull())
    expect(screen.getByTestId('ai-evidence-measured')).toHaveTextContent('0/12')
    expect(document.activeElement).toBe(screen.getByRole('button', { name: 'Add artifact' }))
    fireEvent.click(within(cardOf('Stage 00 · Setup + math by picture') as HTMLElement).getByTestId('board-card-open'))
    expect(within(await screen.findByRole('dialog')).queryByRole('button', { name: 'Delete artifact' })).toBeNull()
  })
})
